### ISSUE TITLE
jar is not working properly

### ISSUE THREAD

**Issue by ghost** [yeokm1/docs-to-pdf-converter#14]
Arun.4.Kumar@0076-TZB-IMS MINGW64 ~/Downloads/docs-to-pdf-converter/docs-to-pdf-converter/target (master)
$ java -jar docs-to-pdf-converter-1.8.jar -i test.docx -o test.pdf
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

Arun.4.Kumar@0076-TZB-IMS MINGW64 ~/Downloads/docs-to-pdf-converter/docs-to-pdf-converter/target (master)

**Comment by yeokm1** [comment]
Hi. I'm not too sure what happened. May I know the platform you are running on?

**Comment by aresares** [comment]
same error for me, Im using windows 10, java 1.8
